name: cla-check
version: git
summary: Check if Canonical's Contributor License Agreement has been signed
description: |
  Most projects at Canonical require contributors to sign the CLA. That
  typically means that one must check to see if a contributor has signed the
  CLA, which is where this snap comes in handy.

  You only need the email address of the contributor; run the snap with the
  following:

      $ cla-check <email address>
      $ cla-check.cla-check-git REVISION..RANGE

  The exit code will be 0 if the CLA has been signed, and non-zero otherwise.

base: core20
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

apps:
  cla-check:
    command: bin/cla-check
    plugs: [network, network-bind]

  cla-check-git:
    command: bin/cla-check-git
    plugs: [network, network-bind, home, removable-media]

parts:
  cla-check:
    plugin: python
    requirements: [requirements.txt]
    source: .
    stage-packages: [git]

    # Required for cryptography
    build-packages: [libssl-dev, libffi-dev]
